// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace SpaceHavoc
{
public static class GPGSIds
{
        public const string achievement_your_first_improvement = "CgkIp4zItNoREAIQBQ"; // <GPGSID>
        public const string achievement_kamikaze = "CgkIp4zItNoREAIQBA"; // <GPGSID>
        public const string achievement_first_start = "CgkIp4zItNoREAIQAQ"; // <GPGSID>
        public const string leaderboard_time_leaderboard = "CgkIp4zItNoREAIQBw"; // <GPGSID>
        public const string leaderboard_score_leaderboard = "CgkIp4zItNoREAIQBg"; // <GPGSID>
        public const string achievement_youve_been_shot = "CgkIp4zItNoREAIQAw"; // <GPGSID>
        public const string package_name = "com.ej.spacehavoc"; // <GPGSID>
        public const string achievement_death_by_meteor = "CgkIp4zItNoREAIQAg"; // <GPGSID>

}
}
